### ISSUE TITLE
multi-size images

### ISSUE THREAD

**Issue by PythonImageDeveloper** [m-nasiri/tensorflow#2]
Hi Nasiri ,
I have some question about convert multi-size images to tfrecord.
Q1) If i have muti-scale images , When turned to tfrecord , Does not cause the problem for Bounding Boxes ? 
Q2) when i want to train the model with tfrecord , this training done only by tfrecord or anno and images are necessary also?

**Comment by majnas** [comment]
Hi,
AQ1: for handling datasets with different size of images use these codes
https://github.com/m-nasiri/tensorflow/tree/master/tfrecord_multishape_image_dataset

AQ2: if u convert all images and annos in a single tfrecord file, you can delete all images and annos then train your model only using tfrecord file.

**Comment by PythonImageDeveloper** [comment]
Thanks , 
I also want to include the [https://www.tensorflow.org/programmers_guide/datasets](url) in the code for increasing the performance.
please put your mail if possible.
